name: "Build with Java 17"
on:
  workflow_dispatch:
  pull_request:
    branches:
    - development
    paths:
    - "src/**"
    - "build.gradle"
jobs:
  build:
    name: "Compile jar with Java 17"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Setup Java 17"
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    - name: "Make gradlew executable"
      run: "chmod +x gradlew"
    - name: "Build jar with Java 17"
      run: "./gradlew shadowJar"
    - name: "Upload build artifact"
      uses: actions/upload-artifact@v4
      with:
        name: jar-build-java17
        path: build/libs/*.jar
        retention-days: 30
